### PR TITLE
Refactor Schemas into LinkedDataFragments Namespace

### PR DESCRIPTION
**Pull request by no-reply**
Moves Schemas into `lib` as a first step in isolating other logic.

### CODE REVIEW

**Comment by scande3** [comment]
Is this in reference to https://github.com/ActiveTriples/linked-data-fragments/issues/38 so that you can run individual tests?

**Comment by no-reply** [comment]
@scande3: It's the first step in a stepwise refactor to move core logic to `lib`. There are follow-up PRs on the way to make the core logic sharable, make the application mountable, and gemify the project.

I'm submitting them in the small refactors like this to keep review sane and ensure we avoid breaking changes.

#38 was encountered along the way. The aggressive stubbing made it hard to extract `Setting` from the rails app.

**Comment by no-reply** [comment]
The first follow-up is here: ~https://github.com/ActiveTriples/linked-data-fragments/tree/feature/refactor-schemas~ https://github.com/ActiveTriples/linked-data-fragments/compare/feature/refactor-models

The best public branch for where things are going is: https://github.com/ActiveTriples/linked-data-fragments/commits/feature/rack-server

**Review by scande3 — APPROVED** [review]
I'm not entirely sure I understand the full need for this refactor but as it doesn't break anything that I can see, going to approve it. Nothing incorrect about any of the code that I noticed. Thanks!

**Pull request merged**
